ManageIQ/manageiq-providers-kubevirt

- app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/power.rb
Few fixes to enable vm power management operations such as stop and start.
Fixed by @jhernand.
> Vm start and stop

- README.md
Let's be consistent with other ManageIQ project and use markdown instead of adoc as README.
> Chanege readme format from adoc to md.

- docs/virtual_machine_template_guide.adoc
Documentation describing how to write a Virtual machine template for ManageIQ
> create a virtual machine template user guide

- manifests/README.adoc
- manifests/example-template-windows.yml
Add example template to build OfflineVirtualMachine
for linux and windows flavours.
> docs: add template examples for kubevirt

- app/models/manageiq/providers/kubevirt/builder.rb
- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
- app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb
- app/models/manageiq/providers/kubevirt/inventory.rb
During retirement process we need to target removed vm during refresh.
This PR fixes the issue with refresh opration.
> Refresh removed vm

- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
We can receive following notices from Kubernetes/Openshift:
#<Kubeclient::Common::WatchNotice type="ERROR",
object={:kind=>"Status",
:apiVersion=>"v1",
:metadata=>{},
:status=>"Failure",
:message=>"too old resource version: 1203002 (1691766)",
:reason=>"Gone",
:code=>410}>
#<Kubeclient::Common::WatchNotice type="ERROR",
object={:kind=>"Status",
:apiVersion=>"v1",
:metadata=>{},
:status=>"Failure",
:message=>"The resourceVersion for the provided watch is too old.",
:reason=>"Expired",
:code=>410}>
For both we need to restart watches since we do not know which object's version
is old. Similar situation occurs when MIQ was down for longer period of time
and we need to run every time full_refresh on MIQ start.
> Watch restart when expiration notice received

- docs/virtual_machine_template_guide.adoc
- manifests/example-template-windows.yml
- manifests/example-template.yml
Update Templates user guide and examples to use the new guest os label introduced in 
https://github.com/kubevirt/user-guide/pull/25 
Signed-off-by: Yanir Quinn yquinn@redhat.com
> Update user guide and examples with guest OS label

- app/models/manageiq/providers/kubevirt/infra_manager.rb
- app/models/manageiq/providers/kubevirt/infra_manager/template.rb
Adding display names for infra manager and for template entities.
> Add display names

- app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb
Remove useless EmsRefresherMixin removed in https://github.com/ManageIQ/manageiq/pull/17472
> Remove useless EmsRefresherMixin

- app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
- manageiq-providers-kubevirt.gemspec
- spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
New version improves exception handling.
> Use new fog-kubevirt version

- manifests/working-template.yml
Changed the default to 1Gi to be aligned with manageiq minimum which is 1Gi
> updated the default value to be aligned with miq

- app/models/manageiq/providers/kubevirt/infra_manager/inventory.rb
- app/models/manageiq/providers/kubevirt/inventory.rb
- app/models/manageiq/providers/kubevirt/inventory/collector.rb
- app/models/manageiq/providers/kubevirt/inventory/parser.rb
- app/models/manageiq/providers/kubevirt/inventory/persister.rb
Move ManagerRefresh::Inventory to ManageIQ::Providers::Inventory
> Move Inventory to ManageIQ::Providers

- lib/manageiq/providers/kubevirt/engine.rb
See ManageIQ/manageiq-ui-classic#4496 for primary motivation.
> Add plugin display name

- spec/factories/template_kubevirt.rb
- spec/factories/vm_kubevirt.rb
- spec/models/manageiq/providers/kubevirt/infra_manager/provision/cloning_spec.rb
- spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/parser_spec.rb
This PR is a followup to ManageIQ/manageiq#18279 where we're updating FactoryGirl to FactoryBot.
> Change FactoryGirl to FactoryBot

- lib/manageiq/providers/kubevirt/engine.rb
Change plugin common methods to class methods
> Change plugin common methods to class methods

- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
See commit: 3dab242eb3a376dfc17e178e37fe93af97aa62e8
> kubeclient was replaced with fog/kubevirt

- app/models/manageiq/providers/kubevirt/infra_manager/template.rb
@agrare Please review.
Part of https://github.com/ManageIQ/manageiq/pull/20486
> Add missing supports :provisioning for templates

- .codeclimate.yml
- .rubocop.yml
- .rubocop_cc.yml
- manageiq-providers-kubevirt.gemspec
Depends On: ManageIQ/miq_bot#506
> Use manageiq-style

- app/models/manageiq/providers/kubevirt/infra_manager.rb
Depends on: https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/410
> Use inheritance not mixins

- app/models/manageiq/providers/kubevirt/inventory/persister.rb
https://github.com/ManageIQ/manageiq/pull/21094
> Don't manually set the template's model_class

- systemd/manageiq-providers-kubevirt_infra_manager_refresh@.service
part of https://github.com/ManageIQ/manageiq-rpm_build/pull/157
using manageiq properties and still running as root (but very close to switching over to manageiq user)
> add properties files to systemd

- systemd/manageiq-providers-kubevirt_infra_manager_refresh@.service
> run services as manageiq user

- app/models/manageiq/providers/kubevirt/infra_manager.rb
- app/models/manageiq/providers/kubevirt/infra_manager/host.rb
- app/models/manageiq/providers/kubevirt/infra_manager/storage.rb
Required for: https://github.com/ManageIQ/manageiq/pull/21597
> Add missing Host/Storage subclasses under Kubevirt

- spec/models/manageiq/providers/kubevirt/inventory/partial_target_refresh_spec.rb
Required for:
* https://github.com/ManageIQ/manageiq/pull/21650
Fixes https://github.com/ManageIQ/manageiq-cross_repo-tests/runs/6598734757?check_suite_focus=true#step:6:2329
> Use a proper factory instead of a double

- app/models/manageiq/providers/kubevirt/infra_manager.rb
Continuing to remove uneeded memoization, with some additional translation fixes.
@miq-bot add-label bug
@miq-bot add-label najdorf/yes?
@miq-bot assign @agrare
> Removing Memoization

- app/models/manageiq/providers/kubevirt/constants.rb
- app/models/manageiq/providers/kubevirt/infra_manager.rb
- app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
- app/models/manageiq/providers/kubevirt/infra_manager/provision.rb
- app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb
- app/models/manageiq/providers/kubevirt/infra_manager/provision/state_machine.rb
- app/models/manageiq/providers/kubevirt/infra_manager/provision_workflow.rb
- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker.rb
- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
- app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb
- app/models/manageiq/providers/kubevirt/infra_manager/template.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/power.rb
- app/models/manageiq/providers/kubevirt/inventory/collector.rb
- app/models/manageiq/providers/kubevirt/inventory/parser.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/full_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/partial_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/partial_target_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/persister.rb
- app/models/manageiq/providers/kubevirt/refresh_memory.rb
- spec/models/manageiq/providers/kubevirt/infra_manager/provision/cloning_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/full_refresh_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/parser_spec.rb
- spec/models/manageiq/providers/kubevirt/inventory/partial_target_refresh_spec.rb
- spec/support/file_helpers.rb
The ManageIQ project is copyright "ManageIQ Authors"
> Remove Red Hat Copyright notice

- manageiq-providers-kubevirt.gemspec
Pulls in https://github.com/fog/fog-kubevirt/pull/156 via https://github.com/fog/fog-kubevirt/pull/160 
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/237
> Bump fog-kubevirt to v1.4.0 for ruby3 fixes

- app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Required for:
* https://github.com/ManageIQ/manageiq-providers-openshift/pull/269
> Allow override of collector/parser/persister classes

- app/models/manageiq/providers/kubevirt/inventory/parser.rb
- spec/fixtures/files/template-without-parameters.yml
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/244
@miq-bot add_label bug, radjabov/yes?
> Fix memory attribute retrieval in parser

- spec/models/manageiq/providers/kubevirt/infra_manager/event_parser_spec.rb
Add specs for vm event parsing
@miq-bot add_label test
> VM event parsing specs

- app/models/manageiq/providers/kubevirt/infra_manager.rb
- app/models/manageiq/providers/kubevirt/infra_manager/host.rb
- app/models/manageiq/providers/kubevirt/infra_manager/metrics_capture.rb
- app/models/manageiq/providers/kubevirt/infra_manager/metrics_capture/prometheus_capture_context.rb
- app/models/manageiq/providers/kubevirt/infra_manager/metrics_collector_worker.rb
- app/models/manageiq/providers/kubevirt/infra_manager/metrics_collector_worker/runner.rb
- app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
- config/settings.yml
- systemd/manageiq-providers-kubevirt_infra_manager_metrics_collector.target
- systemd/manageiq-providers-kubevirt_infra_manager_metrics_collector@.service
Metrics capture for KubeVirt VMs
Depends on:
Needed for:
@miq-bot add_label enhancement
@miq-bot add_reviewers @agrare, @Fryguy
> KubeVirt VM Metrics Capture

- app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
- config/settings.yml
- lib/manageiq/providers/kubevirt/engine.rb
> Add a kubevirt logger

- app/models/manageiq/providers/kubevirt/infra_manager.rb
> Fix alignment of delegate keys

- app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb
- spec/models/manageiq/providers/kubevirt/infra_manager/provision/cloning_spec.rb
Follow-up to https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/276
> VM Clone Cleanups

- app/models/manageiq/providers/kubevirt/inventory/parser.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/full_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/partial_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/parser/partial_target_refresh.rb
- app/models/manageiq/providers/kubevirt/inventory/persister.rb
- spec/models/manageiq/providers/kubevirt/infra_manager/refresher_spec.rb
> Parse host memory and cpu

- .gitignore
- config/secrets.defaults.yml
- lib/manageiq/providers/kubevirt/engine.rb
- spec/config/secrets.defaults.yml
- spec/models/manageiq/providers/kubevirt/infra_manager/refresher_spec.rb
- spec/spec_helper.rb
> Switch to use VcrSecrets helper from core

- lib/manageiq/providers/kubevirt/engine.rb
Depends indirectly on: https://github.com/ManageIQ/manageiq/pull/23509
> Drop to_s on engine paths
