ManageIQ/manageiq-providers-kubevirt

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb
The `kubeclient` gem does not provide exactly the same kind of objects inside notices and inside query responses. That should be fixed by abonas/kubeclient#279. Meanwhile this pull request introduces patches in the provider to avoid the issue.
The first  patch can and should be reverted when the issue in `kubeclient` is fixed. The second one should stay.
=> Avoid kubeclient issue

content/miq_dialogs/miq_provision_kubevirt_dialogs_clone_to_vm.yaml
The provider already supports provisioning of virtual machines from
templates, but the dialog is missing. This patch adds it.
Request tab:
Purpose tab:
Catalog tab:
Hardware tab:
Schedule tab:
=> Add missing `Clone to VM` dialog

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/memory_calculator.rb, manifests/example-template.yml, spec/models/manageiq/providers/kubevirt/memory_calculator_spec.rb
In Kubevirt 0.2.0 the way that virtual machine memory is specified has
changed. In previous versions it was specified like this:
memory:
unit: MB
value: 64
See the example here:
https://github.com/kubevirt/kubevirt/blob/v0.1.0/cluster/vm.yaml#L34-L36
Since version 0.2.0 it is specified like this:
memory: 64M
See the example here:
https://github.com/kubevirt/kubevirt/blob/v0.2.0/cluster/vm.yaml#L10
This means that the `MemoryCalculator` class needs to be changed
accordingly to support the new format.
Also the provision request and the parsing of the reported virtual machines were updated to support the updated memory format.
Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>
Signed-off-by: Moti Asayag <masayag@redhat.com>
=> Adjust the memory calculator to Kubevirt 0.2.0

app/models/manageiq/providers/kubevirt/infra_manager.rb, manageiq-providers-kubevirt.gemspec
The KubeVirt provider will be managed as a secondary provider of
OpenShift/Kubernetes providers.
The endpoint and authentication of kubevirt will reside under the
container providers, selected by the :kubevirt role and authkey.
Adding and removal of KubeVirt should be performed from the container
manager virtualization tab.
Depends on https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/197
=> KubeVirt as a secondary manager of Container Providers

manageiq-providers-kubevirt.gemspec
The project was moved to manageiq organization so we can update it in gemspec file.
=> Update organization in gemspec

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
Currently the provider puts the `RestClient` class in debug mode, doing
the following:
```ruby
RestClient.log = 'stdout'
```
This is a leftover of the initial development of the provider, when it
was very convenient for debugging. But now it should be removed, because
it affects this provider and also any other providers that use the same
gem.
=> Don't put `RestClient` in debug mode

README.md
The token can be obtain by the 'describe' verb of kubectl which can
space the step to decode its value.
=> Update token section in README.md

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
The parameter that the `kubeclient` gem uses to specify the resource
version for a watch is the `:resource_version` symbol, not the
`resourceVersion` string:
https://github.com/abonas/kubeclient/blob/v2.4.0/lib/kubeclient/common.rb#L246
But the provider is using the string `resourceVersion` instead, which is
silently ignored.
=> Use `:resource_version` instead of `resourceVersion`

app/models/manageiq/providers/kubevirt/infra_manager/provision_workflow.rb, content/miq_dialogs/miq_provision_kubevirt_dialogs_template.yaml
Kubevirt is a virtualization provider that allows to create virtual
machines. Currently, it is pretty limited and not fully defined,
therefore the initial dialog allows the user to specific the VM memory
only.
For vm provisioning, the :linked_clone attribute is ignored, as the
decision of disk provision type is made by the storage backend.
In addition, we don't control the node on which the vm will be
scheduled, therefore the implementation of allowed_hosts is irrelevant in this
context.
The core PR that adds kubevirt's template to the eligible templates list:
https://github.com/ManageIQ/manageiq/pull/16873
**Request Tab**
**Catalog Tab**
**Hardware Tab**
**Schedule Tab**
**Invalid name error message**
=> Add VM Provision dialog

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, spec/factories/vm_kubevirt.rb, spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
Kubevirt supports retiring a Vm, regardless its state by removing its
live vm (for running vm) and its offline vm.
=> Support retire VM

manifests/example-template-windows.yml, manifests/example-template.yml
should be "kubevirt" not "kubvirt" (note missing "e")
=> templates: fix typo

manifests/example-template-windows.yml, manifests/example-template.yml, manifests/working-template.yml, spec/fixtures/files/offline_vm.yml, spec/fixtures/files/offline_vm_registry.yml, spec/fixtures/files/offlinevm_registry.json, spec/fixtures/files/template.json, spec/fixtures/files/template_registry.json
There were issues with our example templates. This patch fixes them so
we can use `oc` tool to create them.
=> Make templates consumable by openshift

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
In order to find out if kubevirt is deployed on the kubernetes cluster,
we'll query the reported API versions for the existence of
'kubevirt.io'.
=> Improve kubevirt detection

app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/fixtures/files/vm.json, spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
It is acceptable not to have owner reference when a vm was not created
using offlinevm.
=> Support livevms if provisioned without offlinevms

app/models/manageiq/providers/kubevirt/inventory/collections.rb
Due to missing parent_inventory_collections kubevirt refresh fail.
=> Add parent_inventory_collections to vm.operating_systems

manifests/account-kubernetes.yml, manifests/account-openshift.yml
We do not need kubevirt-infra role in our manifests since it was removed.
It is enough to use cluster-admin.
=> Role kubevirt-infra was removed

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/connection.rb
In order to avoid 404 when kubevirt isn't deployed, the core client
should be used to check if kubevirt version is available.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/44
=> Use core client to query for supported versions

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb, app/models/manageiq/providers/kubevirt/refresh_memory.rb
With previous changes we need to perform full refresh when a worker starts and
whenever watches expire which means we have the latest resource versions. It is
enough to keep them in memory.
=> Stop persisting resource versions

app/models/manageiq/providers/kubevirt/inventory/parser.rb, manifests/working-template.yml, spec/fixtures/files/template.json, spec/fixtures/files/template_registry.json
There is a change in label name how we expose os information.
This PR was pushed because https://github.com/kubevirt/user-guide/pull/25 was merged.
=> Use guest os label

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, content/miq_dialogs/miq_provision_kubevirt_dialogs_clone_to_vm.yaml, content/miq_dialogs/miq_provision_kubevirt_dialogs_template.yaml, spec/fixtures/files/template_registry.json, spec/models/manageiq/providers/kubevirt/infra_manager/provision/cloning_spec.rb
Kubevirt supports memory and cores as hardware attributes.
In order to pass those to kubevirt, a mapping is required to the
expected attribute names on kubevirt side.
=> Respect user hardware attributes

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, manageiq-providers-kubevirt.gemspec
Reverted monkey patch from #2.
https://bugzilla.redhat.com/show_bug.cgi?id=1507528
miq-bot add-label bug, ~~gaprindashvili/yes~~ (this repo didn't exist then)
(On master, we'll later upgrade to kubeclient 3.0.0, need to resolve a version conflict first. On gaprindashvili, we'll stay with 2.5.)
@pkliczewski @masayag @jhernand please review.
=> Bump kubeclient to >=2.5.2 <2.6, drop monkey patch

app/models/manageiq/providers/kubevirt/builder.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/inventory/parser/partial_target_refresh.rb, spec/fixtures/files/collectors/one_offline_vm.json, spec/models/manageiq/providers/kubevirt/inventory/partial_target_refresh_spec.rb
Implement target refresh for vms, offline vms and templates.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/48
=> Target refresh

app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/power.rb
Start from kubevirt v0.4.0, the vm will be powered on only by changing
the status of the offline vm to running.
There no need to explicitly create a live vm entity on vm start or
removing the live vm entity on vm stop.
=> virt controller starts and stops vms

app/models/manageiq/providers/kubevirt/inventory/collections.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/inventory/parser/full_refresh.rb, app/models/manageiq/providers/kubevirt/inventory/parser/partial_refresh.rb, app/models/manageiq/providers/kubevirt/inventory/parser/partial_target_refresh.rb, app/models/manageiq/providers/kubevirt/inventory/persister.rb, spec/fixtures/files/vm.json, spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
Saves the IP address and hostname if exists for a live vm entity.
=> Save network information for live vms

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/fixtures/files/offline_vm.yml, spec/fixtures/files/offline_vm_registry.yml
The OS label should be copied from the template to the offline vm
on creation. It also has to be parsed when offline vm is collected
and parsed, so MIQ will be able to present a proper icon and
description when the vm is being viewed.
=> Save OS label for Offline VM

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, spec/fixtures/files/offline_vm.yml, spec/fixtures/files/offline_vm_registry.yml
kubevirt v0.4.0 expects the :running attribute to be provided, even for an offline vm.
Without it, creation of offlinevm fails with:
> spec.running in body is required
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/59
=> Provide :running attribute

app/models/manageiq/providers/kubevirt/inventory/parser/partial_target_refresh.rb
Do not pass ids to child inventory collections, these are
automatically populated by :parent_inventory_collections option.
Passing them like this will fail with a new assert added to core in [https://github.com/ManageIQ/manageiq/pull/17408]
=> Do not pass ids to child inventory collections

app/models/manageiq/providers/kubevirt/inventory/parser/partial_refresh.rb, app/models/manageiq/providers/kubevirt/inventory/persister.rb
There was a PR merged which not fully cleanup disk collection code used
during target refresh.
=> Finalizing target refresh cleanup

app/models/manageiq/providers/kubevirt/infra_manager.rb
When the token for kubevirt is being provided (i.e. when changing the token by the user), it should be respected and used to verify connectivity and the virtualization support instead of relying on the existing token.
Required by https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/256
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/77
=> Respect kubevirt token if provided

app/models/manageiq/providers/kubevirt/infra_manager/vm.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/refresh_memory.rb, manageiq-providers-kubevirt.gemspec, spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
We assumed about vm status based on part of the flow we were in.
This PR uses vm status as collected from kubevirt.
=> Use vm status provided by kubevirt

content/miq_dialogs/miq_provision_kubevirt_dialogs_template.yaml
The VM name should be restricted by the following limitations:
1. Only alphanumeric characters or '-'.
2. First and last characters must be alphanumeric.
3. Up to 63 characters.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/85
=> Validate VM name based on DNS-1123

app/models/manageiq/providers/kubevirt/infra_manager.rb
The UI expects each provider to report its status.
Since kubevirt uses its own token, it might be valid while the container
provider is invalid.
That causes the default_auth_status in the UI [1] to report a failed
status when editing the kubevirt provider as an infrastructure provider,
since it refers to the status of the parent container manager. As a
result of that failure, the dialog cannot be saved.
For that purpose, the delegated call to authentication_status_ok? should
be implemented on the kubevirt provider side.
[1] https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/controllers/mixins/ems_common_angular.rb#L861
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/71
=> Implement authentication_status_ok? method

app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/models/manageiq/providers/kubevirt/inventory/full_refresh_spec.rb, spec/models/manageiq/providers/kubevirt/inventory/partial_target_refresh_spec.rb
Since there is no storage types support for kubevirt, the UNKNOWN
store type should be used for the meantime.
=> Use UNKNOWN store type for kubevirt storage

app/models/manageiq/providers/kubevirt/infra_manager.rb
The default_auth_status is being used by the UI to detect the validity
of the provider. For kubevirt, the default auth_status refers to the
parent provider, while kubevirt auth_status is detected by the :kubevirt
auth_type.
For that purpose, there is a need to report always 'true' for the
'default_auth_status', so the kubevirt provider can be edited when being
accessed as an infra provider.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/71
=> Implement auth methods

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
When starting the MIQ server with an invalid kubevirt token, there are
no watchers were set and the queue to process them wasn't initialized.
Therefore, in order to get the failure reason properly without
misleading errors, we shouldn't fail for uninitialized variables.
=> Do not fail on before_exit

app/models/manageiq/providers/kubevirt/inventory/parser.rb
Since storage wasn't introduced to fog-kubevirt, there is no information
to report on the location of vms and templates.
However, since the 'location' field is mandatory, preserving the former
'unknown' value explicitly.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1610772
=> Add an explicit unknown location

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Full refresh fails in `ManageIQ::Providers::Kubevirt::InfraManager::RefreshWorker::Runner`.
`ManageIQ::Providers::Inventory.build` should be used instead of `ManageIQ::Providers::Inventory::Kubevirt::Builder.build_full`, which was removed.
---
Fixes **BZ** https://bugzilla.redhat.com/show_bug.cgi?id=1632131
caused by PR: https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/115
---
Steps to reproduce:
Click on Refresh on Kubevirt provider
=> Replaces missing Inventory::Builder in refresh runner

manifests/working-template.yml
Current name rely on local registry which is not available everywhere.
Let's base our template on image available in quay.
Fixes: https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/123
=> Fix image name

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
With recent change [1] we introduced this regression where we stopped calling
parser. This PR fixes the issue.
Fixes: https://bugzilla.redhat.com/1649629
[1] https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/117
=> refresh: Parser was never called

app/models/manageiq/providers/kubevirt/inventory/persister.rb
The shared_options were duplicated from the base persister
=> Remove duplicated persister shared_options

spec/factories/template_kubevirt.rb, spec/factories/vm_kubevirt.rb
Fixes:
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
raw_power_state { "up" }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop
--require rubocop-rspec
--only FactoryBot/AttributeDefinedStatically
--auto-correct
=> Fix deprecation on status attributes

config/initializers/gettext.rb
We no longer need to initialize plugin's own gettext catalog (since it has none).
=> Remove gettext initializer

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
update_attributes and update_attributes! are deprecated starting in Rails 6
See https://rubyinrails.com/2019/04/09/rails-6-1-activerecord-deprecates-update-attributes-methods/ for details and Rails PR links.
=> update_attributes deprecation

app/models/manageiq/providers/kubevirt/infra_manager.rb
Add a method indicating the properties required to create a Kubevirt
provider and implement the common self.verify_credentials interface
method.
https://github.com/ManageIQ/manageiq/issues/18818
=> Add methods for for provider creation pluggable UI

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb
Note, autoload would be nice to use here but since you can only autoload from
the parent namespace, you'd have to use Fog.autoload ..., which loads Fog, making
it pointless to try to delay load things.
=> Delay load fog-kubevirt until doing operations

app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, manageiq-providers-kubevirt.gemspec
Allow for the use of a newer version of kubeclient by bumping fog-kubevirt
=> Update fog-kubevirt to newer version

app/models/manageiq/providers/kubevirt/memory_calculator.rb
Move to BigDecimal(value) instead of BigDecimal.new(value) as this was removed and no longer works on recent rubies (https://github.com/ruby/bigdecimal/blob/master/CHANGES.md#200)
https://github.com/ManageIQ/manageiq/issues/19678
=> BigDecimal#initialize was removed in 2.0.0

app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
Needed for: https://github.com/ManageIQ/manageiq/pull/20222
=> Add supports terminate feature

app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
When an old resource version is passed there is a status object returned with the watch notice that has kind Status code 410 reason Gone.  The top level notice object just has type Error.
See https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/393
=> Fix handling of 410 Gone watch errors

app/models/manageiq/providers/kubevirt/infra_manager/provision_workflow.rb, app/models/manageiq/providers/kubevirt/infra_manager/template.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, spec/models/manageiq/providers/kubevirt/infra_manager/vm/operations_spec.rb
Additionally, convert method definitions such as
```ruby
def supports_port?
true
end
```
to
```ruby
supports :port
```
=> Convert `supports_#{op}?` to `supports?(op)`

.gitignore, lib/manageiq/providers/kubevirt/engine.rb, spec/spec_helper.rb
Kubevirt doesn't have VCR specs so I didn't add a default secrets file but this adds the callout in the Engine and spec_helper for it if needed in the future.
https://github.com/ManageIQ/manageiq/issues/21157
=> Add pluggable provider secrets support

app/models/manageiq/providers/kubevirt/infra_manager.rb
`connection.valid?` doesn't return the same connection which causes a later check for `#virt_supported?` to return `nil` when the connection actually does support virtualization.
The result was even with valid endpoint info and credentials the credential verification would always fail with "unknown error"
```
(byebug) kubevirt
#<ManageIQ::Providers::Kubevirt::InfraManager::Connection:0x0000559626830880 @namespace="default", ...
(byebug) kubevirt.valid?
#<Kubeclient::Resource kind="Namespace", apiVersion="v1", ...
(byebug) kubevirt.valid?.virt_supported? # This is essentially what https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/457/files#diff-1fe0d067134e4f6092c7cf36d13501a6d283dcc890e7279c0de4059af6a49de5L817 was doing
nil
```
=> Fix KubeVirt endpoint verification

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/refresher.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/factories/ext_management_system.rb, spec/models/manageiq/providers/kubevirt/inventory/full_refresh_spec.rb
The KubeVirt specs don't appear to be exercising the refresh well enough, refreshing against a live provider results in three different issues:
1. Listing templates fails (https://github.com/fog/fog-kubevirt/pull/149)
2. Kubevirt::InfraManager::Refresher overrides are out of date, cause save_inventory to fail
3. InventoryObject.type being hard-coded to ::Host, not subclassed under Kubevirt::InfraManager
WIP pending appropriate specs that would have caught these
=> Fix KubeVirt Refresh

manageiq-providers-kubevirt.gemspec
The fog-kubevirt templates call was still hitting the old `/oapi` endpoint, fixed by https://github.com/fog/fog-kubevirt/pull/149
=> Bump kubevirt to 1.3.5 for openshift v4 fix

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
fog-kubevirt has ` @namespace = options[:kubevirt_namespace] || 'default'` so we cannot simply leave this parameter out for now, but `""` has the same effect as leaving it blank
TODO:
=> Collect kubevirt resources across all namespaces

spec/spec_helper.rb
As of https://github.com/ManageIQ/manageiq/pull/22039
core now specifies the fixture path so we need to be explicit when running
these tests.
=> Don't rely on rails magic to find fixtures, be explicit

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/provision.rb, app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/inventory.rb
Zeitwerk completely removes the need for these methods. See also: https://github.com/ManageIQ/manageiq/pull/22854
=> Drop require_nested and include_concern

app/models/manageiq/providers/kubevirt/infra_manager/template.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb
part of:
- https://github.com/ManageIQ/manageiq/pull/22898
Deprecating `unsupported_reason_add`. Returning the string instead
Note, these are all the same:
```ruby
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports_feature2?
unsupported_reason_add(:feature, unsupported_reason(:feature2)) unless supports?(:feature2)
unsupported_reason(:feature2) unless supports?(:feature2)
unsupported_reason(:feature2)
```
=> drop unsupported_reason_add

app/models/manageiq/providers/kubevirt/infra_manager.rb, spec/factories/ext_management_system.rb
Required for:
* https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/518
=> Fix parent_manager class to point to Kubernetes::ContainerManager

app/models/manageiq/providers/kubevirt/infra_manager.rb
I'm working on deploying kubevirt/osv on my crc cluster for a live test, but for now it looks like the catalog item dialog uses the normal provisioning dialogs for the request which is great.
=> Add catalog support for KubeVirt

app/models/manageiq/providers/kubevirt/infra_manager.rb
The parent_manager class had Kubernetes::ContainerManager specified which would result in parent_manager being nil when kubevirt was added to an Openshift::ContainerManager due to ActAsStiLeafClass.
Since the base ContainerManager doesn't have an infra_manager we have to drop the inverse_of.
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/239
=> Fix parent_manager class name

app/models/manageiq/providers/kubevirt/inventory/parser.rb
```
[NoMethodError]: undefined method `/' for nil:NilClass
manageiq-providers-kubevirt/app/models/manageiq/providers/kubevirt/inventory/parser.rb:151:in `process_domain'
```
=> Fix parser exception when memory value is missing

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/inventory/persister.rb
- make use of `:kubevirt` default auth type
- remove mention of OSV from catalog type
- generalize parser 
Depends on:
@miq-bot add_label enhancement
=> Openshift Virtualization subclassing changes

app/models/manageiq/providers/kubevirt/infra_manager.rb, app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/power.rb, app/models/manageiq/providers/kubevirt/inventory/collector.rb, app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/fixtures/files/template-without-parameters.yml, spec/models/manageiq/providers/kubevirt/inventory/parser_spec.rb
- `resource.get(name)` calls are namespace scoped
- since we use the catch-all namespace `""` when initializing the client https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/master/app/models/manageiq/providers/kubevirt/infra_manager.rb#L126, this will work for `resource.all` calls but will not work for `resource.get(name)` calls i.e. https://github.com/fog/fog-kubevirt/blob/master/lib/fog/kubevirt/compute/requests/get_template.rb#L6 and will return a 404
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/241
@miq-bot add_label bug, radjabov/yes?
=> Fix Kubevirt client get resource by name calls

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb, app/models/manageiq/providers/kubevirt/infra_manager/provision_workflow.rb, content/miq_dialogs/miq_provision_kubevirt_dialogs_template.yaml
- `:cloud_user_password` is a necessary parameter needed to provision and is used as the password to the `CloudInitNoCloud` volume found in the available templates:
```
volumes:
- dataVolume:
name: kubevirt-catalog-test0010
name: rootdisk
- cloudInitNoCloud:
userData: |-
#cloud-config
user: fedora
password: ${CLOUD_USER_PASSWORD}
chpasswd: { expire: False }
```
- fog-kubevirt replaces the env var with the option passed https://github.com/fog/fog-kubevirt/blob/master/lib/fog/kubevirt/compute/models/template.rb#L167-L180
Needed for:
- https://github.com/ManageIQ/manageiq-providers-openshift/pull/266
@miq-bot add_labels bug, radjabov/yes?
=> Service Catalog Provisioning Support

app/models/manageiq/providers/kubevirt/infra_manager/refresh_memory.rb, app/models/manageiq/providers/kubevirt/infra_manager/refresh_worker/runner.rb
Better support subclassed providers (aka Openshift) which have the Kubevirt InfraManager in the same vendor namespace as other manager types like a ContainerManager.
Related:
* https://github.com/ManageIQ/manageiq-providers-openshift/pull/268#discussion_r1775606753
=> Move RefreshMemory under InfraManager

app/models/manageiq/providers/kubevirt/infra_manager.rb
Since the parent manager (k8s) has auth records for k8s and kubevirt, we need to specifically get the auth status for kubevirt
Fixes https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/246
@miq-bot add_labels bug, radjabov/yes?
=> Kubevirt authentication status

app/models/manageiq/providers/kubevirt/infra_manager/event_catcher.rb, app/models/manageiq/providers/kubevirt/infra_manager/event_catcher/runner.rb, app/models/manageiq/providers/kubevirt/infra_manager/event_parser.rb, app/models/manageiq/providers/kubevirt/infra_manager/kubernetes_event_monitor.rb, config/settings.yml, systemd/manageiq-providers-kubevirt_infra_manager_event_catcher.target, systemd/manageiq-providers-kubevirt_infra_manager_event_catcher@.service
Events collection for VMs on kubevirt
Needed for:
@miq-bot add_label enhancement
@miq-bot add_reviewer @Fryguy, @agrare
=> KubeVirt Events Capture

config/settings.yml
Adding the necessary events to event_groups to view from the timeline in UI
@miq-bot add_label enhancement
=> Add VM event_groups to settings

app/models/manageiq/providers/kubevirt/inventory/parser.rb, app/models/manageiq/providers/kubevirt/inventory/persister.rb, spec/models/manageiq/providers/kubevirt/inventory/parse_vm_spec.rb
Cherry picked from https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/260
In Kubevirt, hosts are the nodes on which the VMs are deployed. The uid is not available from the VM payload that is returned by the API and so we use the name and add a secondary ref
Needed for:
@miq-bot add_labels enhancement
=> Persist VM with host

app/models/manageiq/providers/kubevirt/infra_manager/vm.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/guest.rb
This PR introduces the "Restart VM" feature for VMs managed by the KubeVirt infrastructure provider in ManageIQ.
Testing:
Verified the restart functionality for KubeVirt VMs via the UI.
Before: "Restart Guest" option is disabled for KubeVirt VMs.
After: "Restart Guest" button available and functional for KubeVirt VMs.
@Fryguy Kindly take a look at this and review the PR. Thank you!
=> Restart a Virtual Machine

README.md, app/models/manageiq/providers/kubevirt/infra_manager/connection.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm.rb
This was removed by kubevirt in https://github.com/kubevirt/kubevirt/pull/618 and replaced with VNC support
Related: https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/268 adding VNC support
=> Remove obsolete SPICE console option

app/models/manageiq/providers/kubevirt/infra_manager/provision/cloning.rb
When provisioning a kubevirt vm the cloud_user_password is being set as the v2-key encrypted string
```
51:   def user_options(options)
52:     merged_options = options.dup
53:     merged_options[:cpu_cores] = get_option(:cores_per_socket)
54:     merged_options[:memory] = get_option(:vm_memory)
55:     merged_options[:cloud_user_password] = get_option(:root_password)
=> 56:     merged_options.compact
57:   end 
58: end 
(byebug) merged_options
{:name=>"ag-prov-test-2", :cpu_cores=>2, :memory=>"1024", :cloud_user_password=>"v2:{jlrF7Hk6l0rK03aF62GIow==}"}
```
=> Fix cloud_user_password v2-key encrypted

app/models/manageiq/providers/kubevirt/inventory/parser.rb, spec/models/manageiq/providers/kubevirt/infra_manager/refresher_spec.rb
Previously we were only looking at "spec.domain.cpu.cores" but if you let kubevirt pick the cpu topology it will set e.g. "4 cpus" as 4 sockets, 1 core, 1 thread:
```
spec:
architecture: amd64
domain:
cpu:
cores: 1
sockets: 4
threads: 1
```
=> Parse VM Sockets and Threads

app/models/manageiq/providers/kubevirt/infra_manager/vm.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/configuration.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/reconfigure.rb, spec/factories/host_kubevirt.rb, spec/models/manageiq/providers/kubevirt/infra_manager/vm/reconfigure_spec.rb
=> VM Reconfigure

app/models/manageiq/providers/kubevirt/infra_manager/vm/operations/configuration.rb, app/models/manageiq/providers/kubevirt/infra_manager/vm/reconfigure.rb
If a VM is created from an instance_type it doesn't have a `spec/template/spec/domain/{cpu,memory}` section but rather a `spec/instancetype` section.
We still need to change the reconfigure dialog to optionally display instance_types instead of just cpu/memory but this gets the API call to kubernetes working.
https://github.com/ManageIQ/manageiq-providers-kubevirt/issues/296
=> Allow VM reconfigure with instance_types / flavors
